# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd src/
        dotnet restore
    - name: Build
      run: |
        cd src/
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd src/
        dotnet test --no-build --verbosity normal
    - uses: actions/upload-artifact@v3
      with:
        name: example-artifact
        path: |
          src/Services/PublishNugetExample/bin/Release/
          !src/Services/PublishNugetExample/bin/Release/net6.0

  publish:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: example-artifact

    - name: Publish to nuget.org
      run: |
        dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
        dotnet nuget push *.nupkg --api-key ${NUGET_ORG_API_KEY} --source nuget.org
