# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:

  release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npx semantic-release

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd src/
        dotnet restore
    - name: Build
      run: |
        cd src/
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd src/
        dotnet test --no-build --verbosity normal
    - uses: actions/upload-artifact@v3
      with:
        name: example-artifact
        path: |
          src/Services/PublishNugetExample/bin/Release/
          !src/Services/PublishNugetExample/bin/Release/net6.0

  publish:

    runs-on: ubuntu-latest
    environment: NuGet Push Integration
    needs: build

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: example-artifact

    - name: Publish to nuget.org
      run: |
        dotnet nuget push *.nupkg --source https://apiint.nugettest.org/v3/index.json --api-key ${{ secrets.NUGET_TEST_API_KEY }} --skip-duplicate
