# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]

jobs:

  release:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    env:
      node-version: 18.x

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
    - name: semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npx semantic-release

  build:

    runs-on: ubuntu-latest
    needs: release

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Pull changes from semantic-release
      run: git pull --rebase
    - uses: ./.github/workflows/composite/build
      with:
        project: ./src/Services/PublishNugetExample
        dotnet-version: 6.0.x
    - uses: actions/upload-artifact@v3
      with:
        name: example-artifact
        path: |
          ./src/Services/PublishNugetExample/bin/Release/
          !./src/Services/PublishNugetExample/bin/Release/net6.0

  publish:

    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: NuGet Integration
    needs: build

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/download-artifact@v3
      with:
        name: example-artifact
    - uses: ./.github/workflows/composite/dotnet-nuget-push
      with:
        nupkg: \*.nupkg
        source: https://apiint.nugettest.org/v3/index.json
        api-key: ${{ secrets.NUGET_TEST_API_KEY }}
