# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet Example

on:
  push:
    branches: [ "main" ]

jobs:

  release:

    runs-on: ubuntu-latest
    environment: semantic-release

    permissions:
      contents: write
      issues: write
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npx semantic-release

  build:

    runs-on: ubuntu-latest
    needs: release

    steps:
    - uses: actions/checkout@v3
    - name: Pull changes from semantic-release
      run: git pull --rebase
    - uses: ./.github/workflows/composite/build
      with:
        project: ./src/Services/PublishNugetExample
        dotnet-version: 6.0.x
    - uses: actions/upload-artifact@v3
      with:
        name: example-artifact
        path: |
          ./src/Services/PublishNugetExample/bin/Release/
          !./src/Services/PublishNugetExample/bin/Release/net6.0

  publish:

    runs-on: ubuntu-latest
    environment: NuGet Push Integration
    needs: build

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: example-artifact

    - name: Publish to nuget.org
      run: |
        dotnet nuget push *.nupkg --source https://apiint.nugettest.org/v3/index.json --api-key ${{ secrets.NUGET_TEST_API_KEY }} --skip-duplicate
